/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.fernandoce.sistnegociosdf.formularios;

/**
 *
 * @author lfern
 */
public class frmMantenimiento extends javax.swing.JPanel {

    /**
     * Creates new form frmMantenimiento
     */
    public frmMantenimiento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabPanel = new javax.swing.JTabbedPane();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "MANTENIMIENTO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Black", 0, 12))); // NOI18N
        add(tabPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1105, 670));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTabbedPane tabPanel;
    // End of variables declaration//GEN-END:variables
}
